name: Sync to Gitee

# on:
  # push:
  #   branches: [main, master]
  # workflow_dispatch:  # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史

      - name: Push to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_KEY }}
        with:
          source-repo: "git@github.com:${{ github.repository }}.git"
          destination-repo: "git@gitee.com:${{ github.repository_owner }}/${{ github.event.repository.name }}.git"
